from enum import Enum
from pydantic import BaseModel, Field, ConfigDict


class ActionType(str, Enum):
    """Types of browser interactions supported by VAR agent."""

    CAPTURE = "capture"
    NAVIGATE = "navigate"
    WAIT = "wait"
    SCROLL = "scroll"
    CLICK = "click"
    TYPE = "type"


class AgentAction(BaseModel):
    """Atomic interaction step executed against web browser."""

    model_config = ConfigDict(frozen=True)

    type: ActionType = Field(..., description="Action type to perform")
    target: str = Field(default="", description="CSS selector or target URL")
    payload: str = Field(
        default="", description="Text to type or wait duration in ms"
    )


class ActionPlan(BaseModel):
    """Planned sequence of actions generated by LLM Vision provider."""

    model_config = ConfigDict(frozen=True)

    actions: list[AgentAction] = Field(
        default_factory=list, description="Ordered sequence of actions"
    )
    rationale: str = Field(
        default="", description="Reasoning behind proposed plan"
    )
    confidence: float = Field(
        default=0.0, description="Confidence score from 0.0 to 1.0"
    )
