from __future__ import annotations

import argparse
import os
from typing import Any, cast


def extract_parser_info(parser: argparse.ArgumentParser) -> dict[str, Any]:
    info: dict[str, Any] = {
        "description": parser.description or "",
        "arguments": [],
        "subcommands": {}
    }

    arguments_list: list[dict[str, Any]] = cast(list[dict[str, Any]], info["arguments"])
    subcommands_dict: dict[str, dict[str, Any]] = cast(dict[str, dict[str, Any]], info["subcommands"])

    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):  # pyright: ignore[reportPrivateUsage]
            raw_choices = getattr(cast(Any, action), "choices", {})
            choices: dict[str, argparse.ArgumentParser] = cast(dict[str, argparse.ArgumentParser], raw_choices) if isinstance(raw_choices, dict) else {}
            for choice, subparser in choices.items():
                subcommands_dict[choice] = extract_parser_info(subparser)
        elif not isinstance(action, argparse._HelpAction):  # pyright: ignore[reportPrivateUsage]
            type_str: str | None = None
            if action.type is not None:
                type_str = str(getattr(action.type, "__name__", type(action.type).__name__))
            arg_info = {
                "flags": list(action.option_strings) if action.option_strings else [action.dest],
                "help": action.help or "",
                "required": action.required,
                "choices": list(action.choices) if action.choices else None,
                "type": type_str
            }
            arguments_list.append(arg_info)

    return info


def generate_markdown(parser_info: dict[str, Any], prog_name: str = "aiwf") -> str:
    lines: list[str] = [
        f"# {prog_name.upper()} CLI Runbook",
        "This document is auto-generated by `runbook_generator.py`. **DO NOT EDIT MANUALLY.**",
        "It provides a complete reference for all commands, flags, and options available in the AIWF CLI.",
        "",
        "## 🤖 AI Agent Instructions (Mandatory)",
        "When you are instructed to use the `aiwf` CLI, you **MUST** follow these rules:",
        "1. **Never guess commands**: If a command or flag is not explicitly listed in this document, it does not exist. Do not hallucinate or invent commands.",
        "2. **Strict syntax**: Pay attention to required arguments vs optional flags.",
        "3. **No extra quotes**: Do not add unnecessary quotes around arguments unless the shell requires it to escape spaces.",
        "4. **Native Execution**: You are operating in a shell environment where `aiwf` is a globally available command. Do not use `python -m workflow_runtime` unless explicitly asked to bypass the wrapper.",
        "",
        "## Release Publication Checkpoint (Mandatory)",
        "For this repository, a local version bump plus `make export` only means the release is **prepared locally**. GitHub does not receive a new version until the nested `public_export` repository is committed, tagged, and pushed.",
        "",
        "When publishing a release that includes `public_export`, agents MUST use this order:",
        "1. Confirm explicit release approval for git write actions (`Continue|Cancel`).",
        "2. Commit and tag the nested `public_export` repository first.",
        "3. Push `public_export` `main` and the release tag to GitHub.",
        "4. Return to the parent repository, stage the updated `public_export` submodule pointer plus release files.",
        "5. Commit, tag, and push the parent repository.",
        "6. Install the published framework back into the current project so local `.agents/` matches the released package:",
        "   - Windows PowerShell: `aiwf update -Force`",
        "   - Unix shells: `aiwf update --force`",
        "7. Verify the local project sees the released version with `aiwf status` or the project version command.",
        "",
        "Verification commands after publication:",
        "```powershell",
        "git -C public_export ls-remote --heads origin main",
        "git -C public_export ls-remote --tags origin vX.Y.Z",
        "git ls-remote --heads origin main",
        "git ls-remote --tags origin vX.Y.Z",
        "aiwf update -Force",
        "aiwf status",
        "git status --short --untracked-files=all",
        "git -C public_export status --short --untracked-files=all",
        "```",
        "",
        "If the target tag is missing from `git -C public_export ls-remote --tags origin vX.Y.Z`, GitHub has not received the public release yet. Do not report the release as published.",
        "",
        "---",
        ""
    ]

    def render_command(name: str, info: dict[str, Any], depth: int = 2) -> None:
        heading = "#" * depth
        lines.append(f"{heading} `{name}`")
        desc = str(info.get("description", ""))
        if desc:
            lines.append(desc)
        lines.append("")

        raw_args = info.get("arguments")
        arguments: list[dict[str, Any]] = cast(list[dict[str, Any]], raw_args) if isinstance(raw_args, list) else []
        if arguments:
            lines.append("**Arguments / Flags:**")
            for arg in arguments:
                raw_flags = arg.get("flags")
                flags_list: list[str] = cast(list[str], raw_flags) if isinstance(raw_flags, list) else []
                flags = ", ".join([f"`{f}`" for f in flags_list])
                req = "(Required)" if arg.get("required") else "(Optional)"
                raw_choices = arg.get("choices")
                choices_list: list[Any] = cast(list[Any], raw_choices) if isinstance(raw_choices, list) else []
                choices = f" [Choices: {', '.join(map(str, choices_list))}]" if choices_list else ""
                detail = f"{arg.get('help', '')}{choices}".rstrip()
                suffix = f": {detail}" if detail else ":"
                lines.append(f"- {flags} {req}{suffix}")
            lines.append("")

        raw_sub = info.get("subcommands")
        subcommands: dict[str, dict[str, Any]] = cast(dict[str, dict[str, Any]], raw_sub) if isinstance(raw_sub, dict) else {}
        if subcommands:
            lines.append("**Subcommands:**")
            for sub_name, sub_info in subcommands.items():
                full_name = f"{name} {sub_name}"
                render_command(full_name, sub_info, depth + 1)

    render_command(prog_name, parser_info, 2)
    return "\n".join(lines)


def generate_and_save_runbook(workspace_root: str = ".") -> None:
    try:
        import importlib
        main_mod = importlib.import_module("workflow_runtime.__main__")
        build_fn: Any = getattr(main_mod, "build_parser", None)
        if not callable(build_fn):
            print("Failed to locate build_parser function in workflow_runtime.__main__")
            return
        parser = cast(argparse.ArgumentParser, build_fn())
    except Exception as e:
        print(f"Failed to load parser for runbook generation: {e}")
        return

    info = extract_parser_info(parser)
    md_content = generate_markdown(info, "aiwf")

    target_dir_root = os.path.join(workspace_root, "runtime")
    target_dir_agents = os.path.join(workspace_root, ".agents", "runtime")

    os.makedirs(target_dir_root, exist_ok=True)
    os.makedirs(target_dir_agents, exist_ok=True)

    target_path_root = os.path.join(target_dir_root, "aiwf-cli-runbook.md")
    target_path_agents = os.path.join(target_dir_agents, "aiwf-cli-runbook.md")

    try:
        with open(target_path_root, "w", encoding="utf-8") as f:
            f.write(md_content)
        print(f"Successfully generated {target_path_root}")

        with open(target_path_agents, "w", encoding="utf-8") as f:
            f.write(md_content)
        print(f"Successfully generated {target_path_agents}")
    except Exception as e:
        print(f"Failed to write CLI runbook: {e}")


if __name__ == '__main__':
    generate_and_save_runbook()
