{{- if and .Values.token (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "msgbus-ws.secretName" . }}
  labels:
    {{- include "msgbus-ws.labels" . | nindent 4 }}
type: Opaque
stringData:
  MSGBUS_TOKEN: {{ .Values.token | quote }}
{{- end }}
