apiVersion: v1
kind: Service
metadata:
  name: {{ include "msgbus-ws.fullname" . }}
  labels:
    {{- include "msgbus-ws.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "msgbus-ws.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
