"""Ports — abstract interfaces the application depends on (Dependency Inversion).

Concrete implementations live in the infrastructure layer and are wired only at
the composition root. Domain/application never import infrastructure.
"""

from __future__ import annotations

from typing import Protocol

from .handoff.seat_state import SeatState
from .locks.lock import Lock
from .mailbox.envelope import Envelope
from .seats.roster import Roster


class RosterRepository(Protocol):
    def exists(self) -> bool: ...
    def load(self) -> Roster: ...
    def save(self, roster: Roster) -> str: ...


class MailboxRepository(Protocol):
    def ensure_inbox(self, slug: str) -> None: ...
    def append(self, slug: str, env: Envelope) -> None: ...
    def read_from(self, slug: str, cursor: int) -> list[Envelope]: ...
    def cursor(self, slug: str) -> int: ...
    def set_cursor(self, slug: str, value: int) -> None: ...


class SeatStateRepository(Protocol):
    def load(self, slug: str) -> SeatState | None: ...
    def save(self, state: SeatState) -> str: ...
    def touch_header(self, slug: str, session_id: str, updated: str) -> None: ...


class BoardRepository(Protocol):
    def render(self, roster: Roster, states: dict) -> str: ...
    def write(self, content: str) -> str: ...


class LockRepository(Protocol):
    def all(self) -> list[Lock]: ...
    def get(self, path: str) -> "Lock | None": ...
    def acquire(
        self, path: str, holder: str, note: str, expires_at: str, force: bool, now_iso: str
    ) -> tuple[str, "Lock | None"]: ...
    def release(self, path: str, holder: str, force: bool) -> bool: ...


class RepoScanner(Protocol):
    def top_level_dirs(self) -> list[str]: ...


class Clock(Protocol):
    def now_iso(self) -> str: ...


class IdGenerator(Protocol):
    def next_id(self, sender_slug: str) -> str: ...


class GitStatusProvider(Protocol):
    def short_status(self) -> str: ...
