// Generated by tools/generate_interactive_docs_skills.js. Do not edit manually.
const skillsData = [
  {
    "name": "aiwf",
    "command": "/aiwf",
    "category": "wrapper",
    "checkpoint": "N/A",
    "purpose": "User-facing entry wrapper for the AI Engineering Workflow Framework (AIWF). Use when the user types aiwf or @aiwf <command> (next, continue, status, tick, coordinator, doctor, state, memory, search, release). Delegates through initialize-workflow to workflow-coordinator; never executes work itself.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "architecture-review",
    "command": "/audit-arch",
    "category": "architecture",
    "checkpoint": "N/A",
    "purpose": "Đánh giá kiến trúc thiết kế giải pháp thiết lập trước khi tạo Technical Design Blueprint.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "blueprint-to-implementation",
    "command": "/implement",
    "category": "workflow",
    "checkpoint": "6",
    "purpose": "Governs the implementation execution lifecycle from a frozen blueprint and valid Implementation Approval. Manages task graph loading, single-writer file governance, pre-write base-hash verification, change ledger recording, static verification, failure/recovery handling, and handoff to debug.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "brainstorming",
    "command": "/brainstorm",
    "category": "workflow",
    "checkpoint": "3",
    "purpose": "Explores, frames, and compares technical solution options from an approved Requirement Specification, evaluates trade-offs and risks, requests Architecture Feasibility Review, and prepares handoff for Plan/Roadmap.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "brainstorming-to-plan",
    "command": "/plan",
    "category": "workflow",
    "checkpoint": "4",
    "purpose": "Constructs delivery roadmaps (milestone-level) and execution plans (task-level) from feasibility-approved brainstorming artifacts, assigns agent roles, enforces safe-write strategies, evaluates Plan Readiness (95/100), requests Plan Architecture Review, and prepares handoff for Technical Blueprint.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "code-standard-review",
    "command": "/code-review",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Use when reviewing implemented code against an approved Blueprint when available, or against an explicit user request and reviewed diff for maintenance/release-only work, plus project rules, coding standards, architecture boundaries, security, maintainability, and testability before validation or release.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "create-adr",
    "command": "/adr",
    "category": "architecture",
    "checkpoint": "N/A",
    "purpose": "Create Architecture Decision Records (ADRs) only when explicitly invoked.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "cross-skill-validation",
    "command": "/cross-skill-validation",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Direct cross-skill validation governance skill for the AI Engineering Workflow framework. Validates end-to-end integration, schema compatibility, enum alignment, authority matrix, artifact identity propagation, and invalidation rules across all AIWF skills.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "csharp-dotnet-pro",
    "command": "/csharp-dotnet",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides advanced C# and .NET development including C#, CSharp, dotnet, .NET 8, .NET 9, ASP.NET Core, EF Core, LINQ, async/await, xUnit, NUnit, Clean Architecture, and Unity C#.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "debug-to-verify",
    "command": "/verify",
    "category": "workflow",
    "checkpoint": "9",
    "purpose": "Governs the evidence consolidation, static verification, acceptance criteria mapping, independent verification review, and final architecture conformance handoff. Enforces Test Authorization guards (tests default to NOT_RUN) and honest limitations reporting.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "devteam",
    "command": "/devteam",
    "category": "orchestration",
    "checkpoint": "N/A",
    "purpose": "DevTeam lets several AI sessions work one repository in parallel without context bloat. A **leader** coordinates; each **dev-seat** owns one non-overlapping slice of the repo. Sessions coordinate through append-only file mailboxes and hand a seat off via a living `seat-state` whose key field is **NEXT STEP NOW**, so a fresh session resumes with zero knowledge loss. It is agent-agnostic: Claude Code, Codex CLI, and Antigravity all interoperate on the same plain files.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "document-compliance-assessment",
    "command": "/verify-doc",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Use when reviewing workflow artifacts, upstream consistency, relative-path compliance, and pre-approval document quality before a phase can pass.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "documentation-synchronization-governance",
    "command": "/documentation-synchronization-governance",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Supports transactional synchronization between source code changes and workflow documentation.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "environment-bootstrap",
    "command": "/bootstrap",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Prepare the local machine for the AI Coding workflow. Installs and configures required tools (Git, Python, Node.js, SQLite, Tree-sitter, QMD), initializes Project Memory configuration, verifies AI Skills, and validates optional infrastructure (Docker, Qdrant, Ollama). Safe components are installed automatically. Unsafe components require explicit user confirmation.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "environment-health",
    "command": "/doctor",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Read-only inspection of the local AI Coding environment. Detects OS, Git, Python, Node.js, Docker, SQLite, Tree-sitter, Qdrant, embedding providers, Ollama, QMD, Project Memory, and required AI Skills. Never modifies anything. Returns a detailed Environment Health Report with actionable recommendations.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "final-audit-and-handoff",
    "command": "/final-audit-and-handoff",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Final audit and handoff governance skill for the AI Engineering Workflow framework. Audits all 18 preceding implementation phases, validates final artifact index, verifies end-to-end traceability, validates operational closure decision, and executes formal redesign project closure.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "frontend-design",
    "command": "/ui",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Design thinking and decision-making for web UI. Use when designing components, layouts, color schemes, typography, or creating aesthetic interfaces. Teaches principles, not fixed values.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "frontend-visual-debug",
    "command": "/visual-debug",
    "category": "workflow",
    "checkpoint": "8",
    "purpose": "Validate frontend implementation visually. Uses browser tools when available to debug and verify frontend UI against the expected design and requirements.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "git-governance",
    "command": "/git-govern",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Governs repository state snapshotting, change scope reconciliation, secret and sensitive content inspection, Git action planning, Git approval validation, commit packaging, pull request planning, and release preparation packaging. Enforces strict read-only execution boundaries when Git/Release approvals are not provided.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "go-development",
    "command": "/go-dev",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides Go development tasks including modules, building, testing, linting, and basic service structure.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "golang-pro",
    "command": "/golang-pro",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides advanced Go programming including concurrency (goroutines, channels), performance profiling, gRPC, generics, and microservices architecture.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "hmr-ui-toolkit",
    "command": "/hmr",
    "category": "frontend",
    "checkpoint": "N/A",
    "purpose": ">",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "implementation-to-debug",
    "command": "/debug",
    "category": "workflow",
    "checkpoint": "7",
    "purpose": "Governs the reproduction, hypothesis tracking, root-cause analysis, and remediation design lifecycle for implementation failures. Enforces patch authorization boundaries (Debug CANNOT edit source directly) and handoff to verification.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "implementation-to-release",
    "command": "/release",
    "category": "workflow",
    "checkpoint": "10",
    "purpose": "Enforces explicit user-driven releases with workflow-aware validation before any release activities.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "initialize-workflow",
    "command": "/init",
    "category": "runtime",
    "checkpoint": "1",
    "purpose": "Mandatory runtime bootstrap initializer for the AI Engineering Workflow. Resolves repository root via git rev-parse --show-toplevel, loads AI_RULES.md + AGENTS.md (all 13 global policies), loads .agents/state AND .agents/memory/walkthrough.md for full prior-session context, validates project identity & active workflow, checks duplicate workflow/orchestrator locks, and issues a SHA-256 validated Bootstrap Receipt.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "knowledge-runtime",
    "command": "/knowledge",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "Unified knowledge layer and provider router for the AI Engineering Workflow framework.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "msgbus-ws",
    "command": "/msgbus",
    "category": "communication",
    "checkpoint": "N/A",
    "purpose": ">",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "notify-telegram",
    "command": "/notify",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "Sends a Telegram push notification to the user (the project owner) whenever Claude reaches a point that needs the user's decision/confirmation before continuing — so the user can respond promptly instead of the session sitting idle waiting.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "plan-to-blueprint",
    "command": "/blueprint",
    "category": "workflow",
    "checkpoint": "5",
    "purpose": "Transforms an architecture-approved execution plan into a production-grade Technical Blueprint, specifying component boundaries, interface contracts, data models, concurrency, error handling, file impact maps, implementation sequences, and verification matrices. Evaluates Blueprint Readiness (95/100), requests Blueprint Architecture Approval, executes Blueprint Freeze, and prepares handoff for Implementation Entry.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "post-release-lifecycle",
    "command": "/post-release",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Thực hiện quy trình vận hành và kiểm tra 10 bước nghiêm ngặt sau khi phát hành phiên bản.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-discovery",
    "command": "/discover",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Discover target project's tech stack (languages, frameworks, tools, platforms, databases, infrastructure) and generate project-profile.json to configure dynamic workflow checkpoints.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-memory-bootstrap",
    "command": "/memory-init",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Perform a full first-run analysis of the project and generate complete Project Memory. Script-First Architecture.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-memory-update",
    "command": "/memory-sync",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Incrementally update Project Memory using Git diff. Script-First Architecture.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-rag-search",
    "command": "/memory-search",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Provide fast semantic retrieval of project knowledge for all AI Skills. Script-First Architecture.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "python-development",
    "command": "/python-dev",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides python development tasks including package management, testing, formatting, and linting.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "python-patterns",
    "command": "/python-patterns",
    "category": "architecture",
    "checkpoint": "N/A",
    "purpose": "Guides python design patterns, architecture decisions, OOP principles, and clean code practices.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "quick-feature",
    "command": "/feature",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Enforces a three-stage workflow (Specification, Blueprint, and Implementation) for quick features, upgraded with v3.2 Mini Spec quality standards and rich planning sections.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "quick-fix",
    "command": "/fix",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Enforces a three-stage workflow (Specification, Blueprint, and Implementation) for quick fixes, upgraded with v3.2 Mini Spec quality standards and rich planning sections.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "raw-intent-normalization",
    "command": "/normalize-intent",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Normalizes raw user prompts into structured Normalized Intent using context discovery, goal separation, ambiguity taxonomy, and risk flags.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "readiness-and-approval-gates",
    "command": "/evaluate-gate",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Evaluates readiness scores (95/100 threshold), enforces strict blocking rules, validates explicit SHA-256 approval records, detects gate bypasses, and logs audit events.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "release-governance",
    "command": "/release-govern",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Governs release readiness assessment, artifact inventory integrity validation, version/changelog/migration/rollback reconciliation, environment and channel target validation, release action taxonomy, release execution planning, post-release verification planning, and final end-to-end workflow handoff. Enforces strict read-only execution boundaries when Release Approval is not provided.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "requirement-specification",
    "command": "/specify-requirements",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Transforms Normalized Intent into a formal Requirement Specification contract before Brainstorming, Roadmap, Plan, Blueprint, and Implementation.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "resume-workflow",
    "command": "/resume",
    "category": "runtime",
    "checkpoint": "Runtime",
    "purpose": "Resume the AI Engineering Workflow from the last recorded checkpoint by reading .agents/.session.json and validating the workspace environment.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "semantic-docs-cleanup",
    "command": "/semantic-docs-cleanup",
    "category": "governance",
    "checkpoint": "N/A",
    "purpose": "Use when cleaning or migrating the project docs directory into semantic feature-family folders. Safely inventories legacy docs, classifies feature families, backs up files, migrates clean tracked artifacts into docs/features/<feature-family>/<stage>/, skips WIP, removes empty obsolete folders, and writes audit reports.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "session-mailbox",
    "command": "/mailbox",
    "category": "communication",
    "checkpoint": "N/A",
    "purpose": ">",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "skill-self-verification",
    "command": "/verify-skill",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Automatically check and verify other Skills within the AI Skill Framework using Behavioral Acceptance Testing (BAT).",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "software-development-workflow",
    "command": "/workflow",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Pure Workflow Orchestrator. Evaluates checkpoints and ensures Blueprint execution and manual Release gates.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "strict-code-block-gate",
    "command": "/strict-code-block-gate",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Use when a Blueprint, approval gate, or implementation entry must validate implementation-ready code blocks across multiple programming languages before source writes.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "system-coordinator-agent",
    "command": "/coordinate",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": ">",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "test-execution-governance",
    "command": "/test-govern",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Governs test requirement analysis, test matrix construction, test execution approval validation, TESTER agent task ownership, test session controls, retry/flaky governance, acceptance evidence reconciliation, final verification decision, and handoff to Git/Release governance.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-investigate",
    "command": "/vir-audit",
    "category": "reasoning",
    "checkpoint": "N/A",
    "purpose": "Cognitive investigation skill for Root Cause Analysis (RCA), contradictions detection, and self-doubt evaluations.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-memory-update",
    "command": "/vir-learn",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Memory consolidation skill promoting visual baselines and compiling lessons learned outcomes.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-runtime",
    "command": "/vir-run",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "AI-facing instruction contract for the deterministic Visual Intelligence Runtime (VIR). Executes sandboxed observations without cognitive logic.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-verify",
    "command": "/vir-check",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Final quality gate verification skill applying weighted consensus, visual audits, and SDLC compliance rules.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "web-design-guidelines",
    "command": "/web-audit",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Review UI code for Web Interface Guidelines compliance. Use when asked to review UI, check accessibility, audit design, review UX, or check site against best practices.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-activation-governance",
    "command": "/activation-govern",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Governs end-to-end audit verification across all 14 redesign phases, activation readiness scoring, activation plan drafting, activation rollback design, and activation approval request handoffs. Enforces strict read-only execution boundaries when Activation Approval is not provided.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-command-audit",
    "command": "/audit-command",
    "category": "audit",
    "checkpoint": "N/A",
    "purpose": "Canonical command-receipt persistence authority for AIWF. Use after a delegated command completes to validate the sanitized Command Receipt, reject any remaining absolute paths, compute and verify its SHA-256 content hash, atomically persist it under .agents/state/audit/commands/, and advance the tamper-evident receipt chain pointer at .agents/state/audit/latest-command.json.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-coordinator",
    "command": "/tick",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "The single canonical entry gate of the AIWF framework. Use at the start of every feature, bug fix, or task request to classify intent, verify the Bootstrap Receipt, load workflow state, enforce the documentation sync gate and approval gates, and dispatch to the correct specialist skill (quick-fix, quick-feature, brainstorming, blueprint-to-implementation, debug, verify, git-governance, release-governance). Specialist skills must never be invoked directly from a raw user prompt.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-runtime",
    "command": "/runtime",
    "category": "runtime",
    "checkpoint": "Runtime",
    "purpose": "Runtime controller for the AI Engineering Workflow. Manages execution session state (.session.json), validates context health, detects context drift, updates checkpoints, supports recovery via resume-workflow, and outputs runtime heartbeats. Read-only.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  }
];
