// Generated by tools/generate_interactive_docs_skills.js. Do not edit manually.
const skillsData = [
  {
    "name": "architecture-review",
    "command": "/architecture-review",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "# Skill: Architecture Review",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "blueprint-to-implementation",
    "command": "/blueprint-to-implementation",
    "category": "tooling",
    "checkpoint": "6",
    "purpose": "Enforces Blueprint validation as the sole inputs for implementation, upgraded to support v3.2 JSON blueprints.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "brainstorming",
    "command": "/brainstorming",
    "category": "tooling",
    "checkpoint": "3",
    "purpose": "Complete, self-contained prompt for the `brainstorming-to-plan` Skill. The Planning Agent must require no further clarification from this section.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "brainstorming-to-plan",
    "command": "/brainstorming-to-plan",
    "category": "tooling",
    "checkpoint": "4",
    "purpose": "Execute a planning prompt from a master brainstorming document and generate a complete, production-ready Implementation Plan under `docs/plans/`.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "code-standard-review",
    "command": "/code-review",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Use when reviewing implemented code against an approved Blueprint when available, or against an explicit user request and reviewed diff for maintenance/release-only work, plus project rules, coding standards, architecture boundaries, security, maintainability, and testability before validation or release.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "create-adr",
    "command": "/create-adr",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "This Skill is used to record and document critical architectural decisions and their trade-offs. It is invoked when `plan-to-blueprint` recommends an ADR, or when a developer determines a significant architecture decision is required.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "csharp-dotnet-pro",
    "command": "/csharp-dotnet",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides advanced C# and .NET development including C#, CSharp, dotnet, .NET 8, .NET 9, ASP.NET Core, EF Core, LINQ, async/await, xUnit, NUnit, Clean Architecture, and Unity C#.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "debug-to-verify",
    "command": "/debug-to-verify",
    "category": "quality",
    "checkpoint": "9",
    "purpose": "Perform a final qualitative and quantitative audit on the active feature implementation to ensure it meets all acceptance criteria, technical design blueprints, and security/performance standards before staging for release.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "document-compliance-assessment",
    "command": "/document-compliance-assessment",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# Skill: document-compliance-assessment (Đánh giá tuân thủ tài liệu)",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "environment-bootstrap",
    "command": "/environment-bootstrap",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "**Prepare and configure** the local machine for the full **Memory-Driven AI Coding Workflow**.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "environment-health",
    "command": "/environment-health",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Perform a **complete, read-only inspection** of the local development environment and return a detailed **Environment Health Report**.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "frontend-design",
    "command": "/ui",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Design thinking and decision-making for web UI. Use when designing components, layouts, color schemes, typography, or creating aesthetic interfaces. Teaches principles, not fixed values.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "frontend-visual-debug",
    "command": "/frontend-visual-debug",
    "category": "quality",
    "checkpoint": "8",
    "purpose": "Validate frontend implementation visually. This Skill acts as the entry-point coordinator for the Visual Intelligence Runtime (VIR).",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "go-development",
    "command": "/go-dev",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides Go development tasks including modules, building, testing, linting, and basic service structure.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "golang-pro",
    "command": "/golang-pro",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides advanced Go programming including concurrency (goroutines, channels), performance profiling, gRPC, generics, and microservices architecture.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "implementation-to-debug",
    "command": "/implementation-to-debug",
    "category": "quality",
    "checkpoint": "7",
    "purpose": "Review the implementation, verify code standards, run targeted validation, debug tests, exercise real runtime cases without mocks/fake data, capture browser evidence when UI is affected, and generate the post-implementation evidence report before final verification.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "implementation-to-release",
    "command": "/implementation-to-release",
    "category": "tooling",
    "checkpoint": "10",
    "purpose": "Enforces explicit user-driven releases with validation matched to the release context.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "initialize-workflow",
    "command": "/initialize-workflow",
    "category": "runtime",
    "checkpoint": "1",
    "purpose": "The `initialize-workflow` Skill compiles a lightweight, unified runtime context so subsequent Skills do not duplicate checks. All expensive operations (memory load, RAG connect, workspace scan, env CLI checks) are deferred to the skills that actually need them via the Runtime Dependency Resolver.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "knowledge-runtime",
    "command": "/knowledge-runtime",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "# Knowledge Runtime Skill",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "notify-telegram",
    "command": "/notify",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "Sends a Telegram push notification to the user (the project owner) whenever Claude reaches a point that needs the user's decision/confirmation before continuing — so the user can respond promptly instead of the session sitting idle waiting.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "okr-report-generator",
    "command": "/okr",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Tự động phân tích hình ảnh bảng OKRs và tạo các báo cáo kỹ thuật summary.md và completed_tasks.md",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "orchestrator",
    "command": "/orchestrator",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "(DEPRECATED) Legacy autonomous execution orchestrator. Use workflow-coordinator instead.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "plan-to-blueprint",
    "command": "/plan-to-blueprint",
    "category": "tooling",
    "checkpoint": "5",
    "purpose": "Generate a production-grade Technical Blueprint (Markdown & JSON) from an approved Implementation Plan using a Memory-First strategy and the FEAT-XXX Feature ID format.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "post-release-lifecycle",
    "command": "/post-release-lifecycle",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# Skill: Post-Release Lifecycle",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-discovery",
    "command": "/project-discovery",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Discover target project's technologies (languages, frameworks, compilers, test frameworks, lint tools, database systems, runtime environments, and infrastructure) and generate `.agents/project-profile.json`.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-memory-bootstrap",
    "command": "/project-memory-bootstrap",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Perform a complete, first-time analysis of the current project and generate all Project Memory layers under `.agents/memory/`.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-memory-update",
    "command": "/project-memory-update",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Perform an incremental update of Project Memory based on files changed since the last memory sync.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-rag-search",
    "command": "/project-rag-search",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Provide semantic retrieval of Project Memory in response to a natural language query.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "python-development",
    "command": "/python-dev",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides python development tasks including package management, testing, formatting, and linting.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "python-patterns",
    "command": "/python-patterns",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# Skill: python-patterns (Python Architecture Patterns)",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "quick-feature",
    "command": "/quick-feature",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Enforces a three-stage workflow (Specification, Blueprint, and Implementation) for quick features, upgraded with v3.2 Mini Spec quality standards and rich planning sections.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "quick-fix",
    "command": "/quick-fix",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Enforces a three-stage workflow (Specification, Blueprint, and Implementation) for quick fixes, upgraded with v3.2 Mini Spec quality standards and rich planning sections.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "resume-workflow",
    "command": "/resume-workflow",
    "category": "runtime",
    "checkpoint": "Runtime",
    "purpose": "The **resume-workflow** Skill allows the user or orchestrator to recover and continue execution from the last valid checkpoint stored in `.agents/.session.json`. It prevents configuration loss, context drift, and branch misalignment.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "semantic-docs-cleanup",
    "command": "/semantic-docs-cleanup",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Clean the `docs/` tree by migrating legacy workflow artifacts into the canonical semantic layout:",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "skill-self-verification",
    "command": "/skill-self-verification",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# Skill: skill-self-verification (Behavioral Acceptance Testing)",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "software-development-workflow",
    "command": "/software-development-workflow",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "This Skill is the **central coordinator** of the entire AI Coding Platform. It acts as a **Project Manager** to determine the current phase, verify Quality Gates, check Blueprint approvals, perform raw request classification, and recommend the single correct next Skill to run.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-investigate",
    "command": "/vir-investigate",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# VIR Investigate Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-memory-update",
    "command": "/vir-memory-update",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "# VIR Memory Update Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-runtime",
    "command": "/vir-runtime",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "# VIR Runtime Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-verify",
    "command": "/vir-verify",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "# VIR Verify Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "web-design-guidelines",
    "command": "/web-audit",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Review UI code for Web Interface Guidelines compliance. Use when asked to review UI, check accessibility, audit design, review UX, or check site against best practices.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-coordinator",
    "command": "/workflow-coordinator",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "The workflow-coordinator skill acts as the stateless entry gate and logical manager of the AI Engineering Workflow. It is invoked on every user tick to parse incoming instructions, enforce gates, load/verify split-state files, check active workflow resume priority, and output deterministic suggestions for the next skill to invoke. It explicitly prohibits the creation of background daemons, heartbeat monitors, or resident loops.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-runtime",
    "command": "/runtime",
    "category": "runtime",
    "checkpoint": "Runtime",
    "purpose": "Runtime controller for the AI Engineering Workflow. Manages execution session state (.session.json), validates context health, detects context drift, updates checkpoints, supports recovery via resume-workflow, and outputs runtime heartbeats. Read-only.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  }
];
