// Generated by tools/generate_interactive_docs_skills.js. Do not edit manually.
const skillsData = [
  {
    "name": "architecture-review",
    "command": "/audit-arch",
    "category": "architecture",
    "checkpoint": "N/A",
    "purpose": "Đánh giá kiến trúc thiết kế giải pháp thiết lập trước khi tạo Technical Design Blueprint.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "blueprint-to-implementation",
    "command": "/implement",
    "category": "workflow",
    "checkpoint": "6",
    "purpose": "Enforces Blueprint validation as the sole inputs for implementation, upgraded to support v3.2 JSON blueprints.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "brainstorming",
    "command": "/brainstorm",
    "category": "workflow",
    "checkpoint": "3",
    "purpose": "Skill definition.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "brainstorming-to-plan",
    "command": "/plan",
    "category": "workflow",
    "checkpoint": "4",
    "purpose": "Convert a structured master brainstorming document into a formal Execution Plan (Markdown & JSON) using a Memory-First strategy and the FEAT-XXX Feature ID format.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "code-standard-review",
    "command": "/code-review",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Use when reviewing implemented code against an approved Blueprint, project rules, coding standards, architecture boundaries, security, maintainability, and testability before validation or release.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "create-adr",
    "command": "/adr",
    "category": "architecture",
    "checkpoint": "N/A",
    "purpose": "Create Architecture Decision Records (ADRs) only when explicitly invoked.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "csharp-dotnet-pro",
    "command": "/csharp-dotnet",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides advanced C# and .NET development including C#, CSharp, dotnet, .NET 8, .NET 9, ASP.NET Core, EF Core, LINQ, async/await, xUnit, NUnit, Clean Architecture, and Unity C#.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "debug-to-verify",
    "command": "/verify",
    "category": "workflow",
    "checkpoint": "9",
    "purpose": "Validate that the feature is production-ready. Enforce standards before release.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "document-compliance-assessment",
    "command": "/verify-doc",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Use when reviewing workflow artifacts, traceability, relative-path compliance, and pre-approval document quality before a phase can pass.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "environment-bootstrap",
    "command": "/bootstrap",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Prepare the local machine for the AI Coding workflow. Installs and configures required tools (Git, Python, Node.js, SQLite, Tree-sitter, QMD), initializes Project Memory configuration, verifies AI Skills, and validates optional infrastructure (Docker, Qdrant, Ollama). Safe components are installed automatically. Unsafe components require explicit user confirmation.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "environment-health",
    "command": "/doctor",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Read-only inspection of the local AI Coding environment. Detects OS, Git, Python, Node.js, Docker, SQLite, Tree-sitter, Qdrant, embedding providers, Ollama, QMD, Project Memory, and required AI Skills. Never modifies anything. Returns a detailed Environment Health Report with actionable recommendations.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "frontend-design",
    "command": "/ui",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Design thinking and decision-making for web UI. Use when designing components, layouts, color schemes, typography, or creating aesthetic interfaces. Teaches principles, not fixed values.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "frontend-visual-debug",
    "command": "/visual-debug",
    "category": "workflow",
    "checkpoint": "8",
    "purpose": "Validate frontend implementation visually. Uses browser tools when available to debug and verify frontend UI against the expected design and requirements.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "go-development",
    "command": "/go-dev",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides Go development tasks including modules, building, testing, linting, and basic service structure.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "golang-pro",
    "command": "/golang-pro",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides advanced Go programming including concurrency (goroutines, channels), performance profiling, gRPC, generics, and microservices architecture.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "implementation-to-debug",
    "command": "/debug",
    "category": "workflow",
    "checkpoint": "7",
    "purpose": "Review the implementation. Identify and resolve problems before verification.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "implementation-to-release",
    "command": "/release",
    "category": "workflow",
    "checkpoint": "10",
    "purpose": "Enforces explicit user-driven releases and requires blueprint validation before any release activities.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "initialize-workflow",
    "command": "/init",
    "category": "runtime",
    "checkpoint": "1",
    "purpose": "Lightweight runtime initializer for the AI Engineering Workflow. Loads mandatory guardrails, reads cached git/state/approval/dashboard context only. Does NOT load full memory, RAG, workspace scan, environment CLI checks, or transcript sync.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "knowledge-runtime",
    "command": "/knowledge-runtime",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "# Knowledge Runtime Skill",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "notify-telegram",
    "command": "/notify",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "Sends a Telegram push notification to the user (the project owner) whenever Claude reaches a point that needs the user's decision/confirmation before continuing — so the user can respond promptly instead of the session sitting idle waiting.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "okr-report-generator",
    "command": "/okr",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Tự động phân tích hình ảnh bảng OKRs và tạo các báo cáo kỹ thuật summary.md và completed_tasks.md",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "orchestrator [DEPRECATED]",
    "command": "/orchestrate",
    "category": "orchestration",
    "checkpoint": "N/A",
    "purpose": "(DEPRECATED) Legacy autonomous execution orchestrator. Use workflow-coordinator instead.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "plan-to-blueprint",
    "command": "/blueprint",
    "category": "workflow",
    "checkpoint": "5",
    "purpose": "Generate a production-grade Technical Blueprint (Markdown & JSON) from an approved Implementation Plan using a Memory-First strategy and the FEAT-XXX Feature ID format.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "post-release-lifecycle",
    "command": "/post-release",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Thực hiện quy trình vận hành và kiểm tra 10 bước nghiêm ngặt sau khi phát hành phiên bản.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-discovery",
    "command": "/discover",
    "category": "environment",
    "checkpoint": "N/A",
    "purpose": "Discover target project's tech stack (languages, frameworks, tools, platforms, databases, infrastructure) and generate project-profile.json to configure dynamic workflow checkpoints.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-memory-bootstrap",
    "command": "/project-memory-bootstrap",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Perform a complete, first-time analysis of the current project and generate all Project Memory layers under `.agents/memory/`.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-memory-update",
    "command": "/project-memory-update",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Perform an incremental update of Project Memory based on files changed since the last memory sync.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "project-rag-search",
    "command": "/project-rag-search",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "Provide semantic retrieval of Project Memory in response to a natural language query.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "python-development",
    "command": "/python-dev",
    "category": "implementation",
    "checkpoint": "N/A",
    "purpose": "Guides python development tasks including package management, testing, formatting, and linting.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "python-patterns",
    "command": "/python-patterns",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# Skill: python-patterns (Python Architecture Patterns)",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "quick-feature",
    "command": "/feature",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Enforces a three-stage workflow (Specification, Blueprint, and Implementation) for quick features, upgraded with v3.2 Mini Spec quality standards and rich planning sections.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "quick-fix",
    "command": "/fix",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "Enforces a three-stage workflow (Specification, Blueprint, and Implementation) for quick fixes, upgraded with v3.2 Mini Spec quality standards and rich planning sections.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "resume-workflow",
    "command": "/resume",
    "category": "runtime",
    "checkpoint": "Runtime",
    "purpose": "Resume the AI Engineering Workflow from the last recorded checkpoint by reading .agents/.session.json and validating the workspace environment.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "semantic-docs-cleanup",
    "command": "/semantic-docs-cleanup",
    "category": "governance",
    "checkpoint": "N/A",
    "purpose": "Use when cleaning or migrating the project docs directory into semantic feature-family folders. Safely inventories legacy docs, classifies feature families, backs up files, migrates clean tracked artifacts into docs/features/<feature-family>/<stage>/, skips WIP, removes empty obsolete folders, and writes audit reports.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "skill-self-verification",
    "command": "/skill-self-verification",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# Skill: skill-self-verification (Behavioral Acceptance Testing)",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "software-development-workflow",
    "command": "/workflow",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Pure Workflow Orchestrator. Evaluates checkpoints and ensures Blueprint execution and manual Release gates.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-investigate",
    "command": "/vir-investigate",
    "category": "tooling",
    "checkpoint": "N/A",
    "purpose": "# VIR Investigate Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-memory-update",
    "command": "/vir-memory-update",
    "category": "memory",
    "checkpoint": "N/A",
    "purpose": "# VIR Memory Update Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-runtime",
    "command": "/vir-runtime",
    "category": "runtime",
    "checkpoint": "N/A",
    "purpose": "# VIR Runtime Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "vir-verify",
    "command": "/vir-verify",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "# VIR Verify Skill Specification",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "web-design-guidelines",
    "command": "/web-audit",
    "category": "quality",
    "checkpoint": "N/A",
    "purpose": "Review UI code for Web Interface Guidelines compliance. Use when asked to review UI, check accessibility, audit design, review UX, or check site against best practices.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-coordinator",
    "command": "/tick",
    "category": "workflow",
    "checkpoint": "N/A",
    "purpose": "Acts as the stateless entry gate and logical manager of the AI Engineering Workflow.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  },
  {
    "name": "workflow-runtime",
    "command": "/runtime",
    "category": "runtime",
    "checkpoint": "Runtime",
    "purpose": "Runtime controller for the AI Engineering Workflow. Manages execution session state (.session.json), validates context health, detects context drift, updates checkpoints, supports recovery via resume-workflow, and outputs runtime heartbeats. Read-only.",
    "input": "See the skill documentation for required inputs and runtime prerequisites.",
    "output": "Skill-specific artifacts, checks, reports, or runtime state updates.",
    "pitfall": "Follow AI_RULES.md, approval gates, and skill-specific hard rules before modifying files."
  }
];
